### ISSUE TITLE
Digest::Digest is deprecated; use Digest

### ISSUE THREAD

**Issue by leeduc** [jwt/ruby-jwt#119]
In Rails 4.2.4, I see this warning from the OpenSSL call within encode when testing use rspec:

```log
/opt/rubystack-2.2.3-2/ruby/lib/ruby/2.2.0/openssl/digest.rb:64
/opt/rubystack-2.2.3-2/ruby/lib/ruby/2.2.0/openssl/digest.rb:64:in `initialize'
/opt/rubystack-2.2.3-2/ruby/lib/ruby/gems/2.2.0/gems/jwt-0.1.8/lib/jwt.rb:33:in `new'
/opt/rubystack-2.2.3-2/ruby/lib/ruby/gems/2.2.0/gems/jwt-0.1.8/lib/jwt.rb:33:in `sign_hmac'
/opt/rubystack-2.2.3-2/ruby/lib/ruby/gems/2.2.0/gems/jwt-0.1.8/lib/jwt.rb:16:in `sign'
/opt/rubystack-2.2.3-2/ruby/lib/ruby/gems/2.2.0/gems/jwt-0.1.8/lib/jwt.rb:53:in `encode'
Digest::Digest is deprecated; use Digest

**Comment by excpt** [comment]
I'd recommend to update you ruby-jwt gem version. It looks like you are using an outdated version (0.1.8).

**Comment by leeduc** [comment]
it's worked, thanks :+1:

**Comment by excpt** [comment]
Great. :)
