### ISSUE TITLE
JWT.encode failing on encode for string

### ISSUE THREAD

**Issue by ShockwaveNN** [jwt/ruby-jwt#235]
Before version 2.0 encoding string with jwt was working fine:
1. Create script `test.rb`
```
require 'jwt'
puts Gem.loaded_specs["jwt"].version
payload = {:data => 'test'}.to_s
p JWT.encode payload, 'pass'
```
2. Install 'ruby-jwt` 1.5.6
3. Run `ruby test.rb`
```
1.5.6
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.Ins6ZGF0YT0-XCJ0ZXN0XCJ9Ig.Ev1hzMBS7GEy2P679zrrb7qtzcDkC6MxTBgpEqLH6d0"
```
4. Install `ruby-jwt` 2.0.0
5. Run `ruby test.rb`
```
2.0.0
/home/lobashov/.rvm/gems/ruby-2.4.2/gems/jwt-2.0.0/lib/jwt/encode.rb:31:in `encoded_payload': undefined method `key?' for "{:data=>\"test\"}":String (NoMethodError)
        from /home/lobashov/.rvm/gems/ruby-2.4.2/gems/jwt-2.0.0/lib/jwt/encode.rb:46:in `encode_segments'
        from /home/lobashov/.rvm/gems/ruby-2.4.2/gems/jwt-2.0.0/lib/jwt/encode.rb:20:in `initialize'
        from /home/lobashov/.rvm/gems/ruby-2.4.2/gems/jwt-2.0.0/lib/jwt.rb:21:in `new'
        from /home/lobashov/.rvm/gems/ruby-2.4.2/gems/jwt-2.0.0/lib/jwt.rb:21:in `encode'
        from test.rb:4:in `<main>'
```

Is this works as intended or is it a bug?
In Changelog there is line `Error with method sign for String #171`, but seems #171 have nothging to do with payload, only with private key

**Comment by ab320012** [comment]
how many types should this arguement support? Hash#to_s, Hash.to_json, and Hash? 

Will a type conversion like the following + tests work? It tentatively supports all 3 
```ruby
# encode.rb
def initialize payload
  @payload = JSON.parse(payload.to_s.gsub(/:(\w+)/){"\"#{$1}\""}.gsub('=>', ':'))
end
```

**Comment by excpt** [comment]
@ShockwaveNN, @ab320012 have a look at https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/encode.rb#L31

Adding `!@payload.is_a?(String)` to the check conditions should solve that problem.

**Comment by ShockwaveNN** [comment]
@excpt I think so
BTW checking condition on this line becoming a lengthy, maybe need some refactor

**Comment by ab320012** [comment]
@expt @ShockwaveNN Hash#to_json returns a string, is that not a valid input?
