### ISSUE TITLE
ArgumentError: invalid base64 while calling JWT::JWK.import(hash)

### ISSUE THREAD

**Issue by AbhishekJadav2** [jwt/ruby-jwt#361]
My current ruby version is **2.2.2** which is greater than minimal ruby version requirement (>=2.1) as per .gemspec file **spec.required_ruby_version = '>= 2.1'*

Here's the full Stack Trace.
```
ArgumentError: invalid base64
	from /home/viraj/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:77:in `unpack'
	from /home/viraj/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:77:in `strict_decode64'
	from /home/viraj/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/base64.rb:95:in `urlsafe_decode64'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/jwt-2.2.1/lib/jwt/jwk/rsa.rb:40:in `import'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/jwt-2.2.1/lib/jwt/jwk.rb:19:in `import'
	from (irb):21
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/viraj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
```

Tested same with ruby **2.5.7** and **2.6.3** and works perfectly.
Please help

Thanks in advance.

**Comment by iiewad** [comment]
+1
