### ISSUE TITLE
JWT encoded using RS256 has invalid signature

### ISSUE THREAD

**Issue by raphael-sales** [jwt/ruby-jwt#482]
Hi,

I'm using version 2.3.0 to create JWT tokens and have been getting invalid tokens from `JWT.encode` when using the `RS256` algorithm

Steps to reproduce:
```
payload = {
  exp: (Time.now.utc + 3600).to_i,
  iss: 1,
  sub: 1,
  aud: 'http://mock-url/',
}
signing_key = OpenSSL::PKey::RSA.generate 2048
token = JWT.encode(payload, signing_key, 'RS256')
```

An example token generated by this snippet:
```
eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2NTQyNDY3NjgsImlzcyI6MSwic3ViIjoxLCJhdWQiOiJodHRwOi8vbW9jay11cmwvIn0.7yn2YIjeEIFGu4tyqlqdNLcUyvKhsXJr7mXbXld26U7qdBmYslBaTXUzv99nnMaqIkqSih0AkcAUhvzoN-0z_CFlLGpc22PXfh1mZ49byaX9F3iezt9Ks6s0Lhq1ntqUCCDI-m9ifU1QblftvSEict5EASwCLoUiedXNH-g39uvKXLTebIU6VpddBsEvuj9ywYy45KWev9XJcxyyOo2PZy8acDKb8XERzdL-_-SYf8q7VJHmvolB8xTP_sQTCTK7owiFHRarnktIgtOXGAEvZ7mmwQV3ogdOXVpq1t1IqWussyjJg6DA3EFWixa4SJJggqMUzonSZKCKNIZWGLXSjg
```

This will then cause validation problems in the decode part as it will have an invalid signature.

I'm using a Mac M1, so I'm not sure if this is a problem related to my own environment or some native library misbehaving. 

Could use some help in shedding some light into this one.

**Comment by raphael-sales** [comment]
I've since reproduced this in a x86/64 system with Ubuntu server, so it doesn't seem to be related to M1 or ARM.

Ruby version 2.7.4

**Comment by bellebaum** [comment]
The JWS looks fine to me, and I have no problems decoding. How did you try to verify the token?

Full example:

```ruby
require 'openssl'
require 'jwt'

payload = {
  exp: (Time.now.utc + 3600).to_i,
  iss: 1,
  sub: 1,
  aud: 'http://mock-url/',
}
signing_key = OpenSSL::PKey::RSA.generate 2048
token = JWT.encode(payload, signing_key, 'RS256')

puts (JWT.decode token, signing_key.public_key, true, {algorithms: 'RS256'})
```

**Comment by raphael-sales** [comment]
@bellebaum when I go to jwt.io, it complains about its signature [here](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2NTQ1ODgwMzUsImlzcyI6MSwic3ViIjoxLCJhdWQiOiJodHRwOi8vbW9jay11cmwvIn0.GXXaX1Vg2kyf7TGTxNbIfaHSvRaGqnwWhupEyin0g354AErEsIV5sNcuD3eF0qDc6MQ5QazlXiq-BQ8eZlMen8j_Xu21HTI3LNnoIytR-2JiJft7SQJsS2N_fd7vFn2SBhVHIVx4aqRmIx0A5Lr36x84PCPgLCB_m6jis71dBohpoXn9Pm4caVkkiz4zgYwJ34t_nzt__OQC6FB8sojtrcJ6vhfb-rlyZHBotL8zzWUCm8hzkKFpTa-qqHvOJ4mluXtNmbR-bc4SDmRFWaMu15T4LpYl6Dp1M1L4z993nw5pteqHKH37Hp1i2rAyzsVzY_lLynWFl0Vg_mGuz3shxw)

And while your full example did work, when I try to run it in two separate contexts, I get a` #<JWT::VerificationError: Signature verification raised>`

Encode token:
```
require 'openssl'
require 'jwt'

payload = {
  exp: (Time.now.utc + 3600).to_i,
  iss: 1,
  sub: 1,
  aud: 'http://mock-url/',
}
signing_key = OpenSSL::PKey::RSA.generate 2048
token = JWT.encode(payload, signing_key, 'RS256')
puts (token)
puts (signing_key.public_key)
puts (JWT.decode token, signing_key.public_key, true, {algorithms: 'RS256'}) 
```

Decode token:
```
require 'openssl'
require 'jwt'

token = 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2NTQ1ODk2NzIsImlzcyI6MSwic3ViIjoxLCJhdWQiOiJodHRwOi8vbW9jay11cmwvIn0.M2C-acrO8DnWXW1tvnhHVen2yN3HLjt9vHZWb6G2SzyELo88sfMPVxr15_aeUcdW3DnEbRFibpsrxYHf298DPHyWVsm6HVMNWhO9Xc82O6tmYLmDKGrE2IyaBh1Qloswp3SvXL8FCVMjk8qQzhgbOaaDmEcwq-qis_NMbj6rOINngvbc7dAyT9M1b1voVRYWHh1QTr6RqmUz0UHNXdOW2dkK3mHYT5ttz-lPtqhmzv1p5XwO811bC1Qm8M_goRqFxL5Xm9KtlS20ulY4M_6-uuDuJ4I-cL147CxQWp2i4eGuQSYAz7E0zRUPlJ1KxjbIEtN8o5-Jt8FEIWcSg4xvoQ'
public_key = "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw5ZSsAU7Au5IqbjOmznH
N4lAfNzePzapI29xAXeQ/GTcZCM2H3i56WDBjHWyZ1FDPlWTQiC52WYJMvVQPuz0
kQgUb5ymvjLBcTnXgEJVnFq8ILGuBCTZYoJjTBmTi4kBykdLhSn6nSMrKrerfvgm
alw2c9NCs9v96D9KaMgk2w89ArYkQ0VBi2rnBf4kGq60dAFXwwwcBIYhL5gdK7h6
uVn3NkrqPj9cJaGfUVuEEcwZ4TCMxILjxhAFYFFx5t0q3+RB3Ftd3VvsGcdmLCOd
KN00hY2NUV1o4r3PCNKwY5l4avlEtJlazbfYAFTAP2IamN2EgnMXv8mKG33VS3GN
cQIDAQAB
-----END PUBLIC KEY-----"
signing_key = OpenSSL::PKey::RSA.new(public_key)
puts (JWT.decode token, signing_key, true, {algorithms: 'RS256'})    
```

It will trigger this:
```
Traceback (most recent call last):
	4: from -:15:in `<main>'
	3: from /Users/raphael/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/jwt-2.3.0/lib/jwt.rb:28:in `decode'
	2: from /Users/raphael/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/jwt-2.3.0/lib/jwt/decode.rb:26:in `decode_segments'
	1: from /Users/raphael/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/jwt-2.3.0/lib/jwt/decode.rb:43:in `verify_signature'
/Users/raphael/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/jwt-2.3.0/lib/jwt/signature.rb:32:in `verify': Signature verification raised (JWT::VerificationError)
```

**Comment by bellebaum** [comment]
I have had problems with jwt.io before when trying to verify signatures.
Recreating your example, I did not get an error.

Decoding example (using a new key and token):

```ruby
require 'openssl'
require 'jwt'

token = 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2NTQ1OTIwNTksImlzcyI6MSwic3ViIjoxLCJhdWQiOiJodHRwOi8vbW9jay11cmwvIn0.pVrR1cj5CTjPyhWMEgQk9zvf7GZBsrxfVSg5-hAhHiI1Lf7Q3vgHlLA3KGVPDmcPTpJGKAt_zOgVlbucYQ3fIxOpdQj6X_xBlQYwzdEPEZDGIWbDdWP0ytvfj9cd5oiOVDnOnPHRx-zdjUcAe0RnZRC-UKzXfOC4FIpqJPhh-G5_UKATOTEBLj7t_HWe5DypvfyNE6FWXZF7YhsfpMdF2hwLOffmqJjnbsMVonSt0ZKN3ffISvOP15HGs8hma_d-neaYQh76co_d8UMf8F13JwJGIvSrNWgCbw_h0atCtmQmLafQ-fQ9cvsRW0ueCowS6iCQCkTISUf6UbxErPnacw'
pem = "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr2+KCFU/K0qO3An5ZWzu
I174WET0SEqtWE501SyMVV9bHfKHb8UC3CVGmDWslmPrg8dSBCn3jK4cNhEZhjiH
/x2tmsIryx8DVKhyqnd/ip+Po45vUmVyVcs9yxkL5UUQP5lefNBXbIEGBjcTkihD
hGpkgN3xT/OZ8vC4U7eTFSCy9tcqXqIfJWr2rfI4NxTbAKw9COxpqa5iHqLdVnrg
yyKirh34zEadyrRl2S6WOr4xlpo4O2eXfDLlFubI93eDtu1HO0c+H/Ab2dZ2psLG
6yvZHz1PpWEcfxspaFPHgg0xqi829KVDHY5f5r8g5I3Z+fM3aXs6ittmzMwnlcGC
vwIDAQAB
-----END PUBLIC KEY-----"
pk = OpenSSL::PKey::RSA.new(pem)

puts (JWT.decode token, pk, true, {algorithms: 'RS256'})
```

**Comment by raphael-sales** [comment]
Such a Magic/More Magic [moment](http://catb.org/esr/jargon/html/magic-story.html). Your example worked and now I can't reproduce the problem anymore.

So weird.

**Comment by raphael-sales** [comment]
Ok, it was my bad, I needed to stub the JWKs properly. Apologies for the trouble
